import React from 'react';
import Layout from '../../../components/layout/Layout';
import { FaChevronRight } from "react-icons/fa";

import './Legal.css';

const TermsOfUse = () => {
    return (
        <Layout>
            <div className="policy-page-wrapper">

                <div className="policy-grid-layout">

                    {/* Main Content Column */}
                    <main className="policy-main-content">

                        {/* Blue Hero Banner */}
                        <section className="policy-hero-banner">
                            <div className="hero-text-content">
                                <h1>Terms of Use</h1>
                                <p>This page outlines the rules, responsibilities, and rights related to using ERONIX website and purchasing our products.</p>
                                
                            </div>
                            <div className="hero-visual-graphics">
                                <svg width="180" height="120" viewBox="0 0 180 120" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <rect x="30" y="30" width="80" height="55" rx="6" fill="#3A86FF" stroke="#333" strokeWidth="2" />
                                    <path d="M30 50h80M30 65h60" stroke="#333" strokeWidth="2" />
                                    <circle cx="135" cy="45" r="20" fill="#FFBE0B" stroke="#333" strokeWidth="2" />
                                    <path d="M135 38v14M128 45h14" stroke="#333" strokeWidth="2.5" strokeLinecap="round" />
                                    <path d="M55 22l15 12 15-12" stroke="#70E000" strokeWidth="3" strokeLinecap="round" />
                                    <rect x="130" y="75" width="35" height="25" rx="4" fill="#DDB088" stroke="#333" strokeWidth="2" />
                                    <path d="M130 85h35M138 93h12" stroke="#333" strokeWidth="2" />
                                </svg>
                            </div>
                        </section>

                        {/* === FULL LEGAL CONTENT === */}

                        {/* Document Notice */}
                        <section className="policy-card-block policy-overview-section">
                            <h2>Document Notice</h2>
                            <p className="intro-text">
                                This document is an electronic record in compliance with the Information Technology Act, 2000, and its associated rules and amendments regarding electronic records. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which mandates publishing the rules and regulations, Privacy Policy, and Terms of Use for accessing or using Eronixtech.com and its associated mobile application (“Platform”). The Platform is owned by Eronix Technologies, a sole proprietorship with its registered office at 1, Jijamata Complex, near India Tea, opposite Sangameshwar College, Sat Rasta, Solapur 413003 (hereinafter referred to as “Eronix Technologies”).
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Your use of the Platform and its services and tools is governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform, including applicable policies which are incorporated herein by reference. If you transact on the Platform, you will be subject to the policies applicable for such transactions. By merely using the Platform, you are contracting with Eronix Technologies, and these terms and conditions, including the policies, constitute your binding obligations with Eronix Technologies.
                            </p>
                        </section>

                        {/* Definitions */}
                        <section className="policy-card-block">
                            <h2>1. Definitions</h2>
                            <p>
                                <strong>“You” or “User”:</strong> Any natural or legal person who has agreed to become a buyer on the Platform by providing registration data while registering as a user using computer systems. Eronix Technologies allows Users to surf the Platform without registering.
                            </p>
                            <p style={{ marginTop: '0.5rem' }}>
                                <strong>“We”, “Us”, “Our”:</strong> Eronix Technologies.
                            </p>
                        </section>

                        {/* Services and Rules */}
                        <section className="policy-card-block">
                            <h2>2. Services and Rules</h2>
                            <p>
                                When you use any of the services provided by us through the Platform, including but not limited to product reviews, seller reviews, applications, and tools, you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such services, which are incorporated into these Terms of Use by reference.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                We reserve the right, at our sole discretion, to modify, amend, add to, or remove portions of these Terms of Use at any time. Any revised version shall be effective immediately upon being posted on the Platform. It is your responsibility to review these Terms of Use periodically for any updates or changes. Your continued use of the Platform after the posting of such changes constitutes your acceptance of and agreement to the revised Terms of Use.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Subject to your compliance with these Terms of Use, we grant you a personal, limited, non-exclusive, non-transferable, and revocable license to access and use the Platform.
                            </p>
                        </section>

                        {/* Acceptance of Terms */}
                        <section className="policy-card-block">
                            <h2>3. Acceptance of Terms</h2>
                            <p>
                                By accessing, browsing, or otherwise using the Platform, you signify your agreement to all the terms and conditions set forth under these Terms of Use. Please read these Terms of Use carefully before proceeding. By implicitly or expressly accepting these Terms of Use, you also agree to be bound by Eronix’s policies, including but not limited to the Privacy Policy (available on the Platform), as amended from time to time.
                            </p>
                        </section>

                        {/* Transaction-Specific Terms */}
                        <section className="policy-card-block">
                            <h2>4. Transaction-Specific Terms</h2>
                            <p>
                                If you engage in any transaction on the Platform, the Terms of Use and policies applicable to that specific transaction shall govern such transaction.
                            </p>
                        </section>

                        {/* Membership Eligibility */}
                        <section className="policy-card-block">
                            <h2>5. Membership Eligibility</h2>
                            <p>
                                Use of the Platform is available only to persons who are competent to form legally binding contracts under the Indian Contract Act, 1872. Persons who are deemed “incompetent to contract” within the meaning of the Indian Contract Act, 1872, including minors and undischarged insolvents, are not eligible to use the Platform.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                If you are under the age of eighteen (18) years, you shall not register as a user of the Platform or engage in any transactions or use of the Platform. Any access, use, or transaction on the Platform by a minor must be undertaken only by their parent or legal guardian.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Eronix reserves the right to terminate or suspend your membership and/or deny access to the Platform if it is discovered that you are under eighteen (18) years of age.
                            </p>
                        </section>

                        {/* User Responsibilities */}
                        <section className="policy-card-block">
                            <h2>6. User Responsibilities</h2>
                            <p>
                                <strong>Account Security:</strong> You are responsible for maintaining the confidentiality of your username and password and for all activities that occur under your account.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                <strong>Prohibited Activities:</strong> You agree not to engage in any of the following activities:
                            </p>
                            <ul style={{ marginTop: '0.5rem', paddingLeft: '1.5rem', listStyle: 'disc' }}>
                                <li style={{ marginBottom: '0.5rem' }}>Violating any applicable laws or regulations.</li>
                                <li style={{ marginBottom: '0.5rem' }}>Infringing the intellectual property rights of others.</li>
                                <li style={{ marginBottom: '0.5rem' }}>Distributing viruses or any other technologies that may harm the Platform or its users.</li>
                                <li>Engaging in any activity that interferes with or disrupts the functioning of the Platform.</li>
                            </ul>
                        </section>

                        {/* Communications */}
                        <section className="policy-card-block">
                            <h2>7. Communications</h2>
                            <p>
                                By using the Platform or contacting us through email or any other form of electronic data transmission, you acknowledge and agree that you are engaging in electronic communication with us. You consent to receive communications from us electronically and agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                We may communicate with you via email or other electronic means, and such communications shall be deemed to constitute valid notice and service of electronic records.
                            </p>
                        </section>

                        {/* Limitation of Liability */}
                        <section className="policy-card-block">
                            <h2>8. Limitation of Liability</h2>
                            <p>
                                In no event shall Eronix be liable for any indirect, incidental, special, consequential, or exemplary damages arising out of or in connection with your use of the Platform.
                            </p>
                        </section>

                        {/* Governing Law and Jurisdiction */}
                        <section className="policy-card-block">
                            <h2>9. Governing Law and Jurisdiction</h2>
                            <p>
                                These Terms of Use shall be governed by and construed in accordance with the laws of India. Any dispute arising out of or in connection with these Terms of Use shall be subject to the exclusive jurisdiction of the courts located in Solapur, Maharashtra.
                            </p>
                        </section>

                        {/* Platform for Transaction and Communication */}
                        <section className="policy-card-block">
                            <h2>10. Platform for Transaction and Communication</h2>
                            <p>
                                The Platform serves solely as a venue to enable Users to interact and conduct transactions with each other. Eronix is not and cannot be a party to, or involved in, any transaction between Users of the Platform. Accordingly:
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Commercial Terms Between Buyers and Sellers</h3>
                            <p>
                                All commercial and contractual terms are offered by, and agreed upon solely between, buyers and sellers. Such terms include, without limitation, price, shipping costs, payment methods, payment terms, delivery timelines, delivery modes, warranties, and after-sales services. Eronix does not determine, control, influence, or participate in the negotiation or agreement of these terms.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Order Placement and Acceptance</h3>
                            <p>
                                When a buyer places an order on the Platform, it constitutes an offer to purchase the listed product(s). Such order does not constitute acceptance by the seller. The seller reserves the right, at its sole discretion, to accept or cancel any order, and the buyer shall be notified of such cancellation via email or SMS.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                In the event of cancellation, any payment received from the buyer shall be refunded in accordance with applicable policies. Sellers may also cancel orders where they reasonably believe the quantities ordered exceed normal individual consumption limits, whether in a single order or multiple cumulative orders. Determination of normal consumption shall vary based on product type and other relevant factors and shall remain at the seller’s discretion.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>No Warranty or Endorsement</h3>
                            <p>
                                Eronix makes no representations or warranties of any kind, express or implied, regarding the products or services listed on the Platform, including but not limited to merchantability, quality, value, fitness for a particular purpose, or saleability. Eronix does not endorse or support the sale or purchase of any products or services listed on the Platform and shall not be liable for any errors or omissions, whether attributable to itself or to third parties.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>No Liability for Seller Performance</h3>
                            <p>
                                Eronix shall not be liable for any non-performance, delay, deficiency, or breach of any contract between buyers and sellers. Eronix does not guarantee that transactions initiated on the Platform will be completed and does not mediate or resolve disputes between buyers and sellers.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>User Verification</h3>
                            <p>
                                Eronix makes no representations or warranties regarding the legal title, identity, or creditworthiness of any User. Users are advised to independently verify the authenticity and credentials of other Users and to exercise due diligence and judgment while transacting.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>No Possession or Ownership of Goods</h3>
                            <p>
                                At no point does Eronix take possession of, or claim any right, title, or interest in, the products or services offered on the Platform. Eronix is not responsible for unsatisfactory performance, delays, damages, or non-availability of products, including those that are out of stock or back-ordered.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Marketplace Role Clarification</h3>
                            <p>
                                The Platform operates strictly as a marketplace that facilitates communication between buyers and third-party sellers. Eronix only provides the technological infrastructure and does not enter into any sale or purchase contract, which remains solely between the buyer and the seller.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>User Responsibility</h3>
                            <p>
                                You are solely responsible for independently agreeing upon delivery, payment, insurance, and other transaction-related terms with the sellers you transact with.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Pricing Disclaimer and Risk Acknowledgement</h3>
                            <p>
                                Product prices displayed on the Platform may be incorrect due to technical issues, typographical errors, or inaccurate information provided by sellers. In such cases, sellers reserve the right to cancel orders. Users acknowledge the risks associated with dealing with underage individuals or persons misrepresenting their identity.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Regulatory Compliance (Marketplace Model)</h3>
                            <p>
                                In accordance with Press Note No. 3 (2016 Series) issued by the Department of Industrial Policy and Promotion (DIPP), Ministry of Commerce and Industry, Government of India, dated March 29, 2016:
                            </p>
                            <ul style={{ marginTop: '0.5rem', paddingLeft: '1.5rem', listStyle: 'disc' }}>
                                <li style={{ marginBottom: '0.5rem' }}>Post-sale delivery of goods and customer satisfaction are the seller’s responsibility.</li>
                                <li style={{ marginBottom: '0.5rem' }}>Payments in a marketplace model may be facilitated by an e-commerce entity in compliance with Reserve Bank of India guidelines.</li>
                                <li>Any warranties or guarantees for goods or services are the sole responsibility of the seller.</li>
                            </ul>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Indemnity and User Content Disclaimer</h3>
                            <p>
                                You agree to release and indemnify Eronix, its affiliates, and their respective directors, officers, employees, and representatives from any losses, damages, liabilities, or consequences arising from the actions or omissions of Platform Users. While Eronix makes reasonable efforts, it cannot control information provided by Users, which may be inaccurate, misleading, offensive, or harmful. Users are advised to exercise caution and follow safe trading practices while using the Platform.
                            </p>
                        </section>

                        {/* Charges */}
                        <section className="policy-card-block">
                            <h2>11. Charges</h2>
                            <p>
                                Membership on the Platform is free for buyers. Eronix does not charge any fees for browsing or purchasing products on the Platform. However, Eronix reserves the right to modify its fee policy at any time at its sole discretion.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                In particular, Eronix may introduce new services and modify or discontinue any of the existing services offered on the Platform. In such cases, Eronix reserves the right to charge fees for such new services or revise the fees applicable to existing services.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Any changes to the fee policy shall be posted on the Platform and shall become effective immediately upon such posting. Unless otherwise specified, all fees shall be quoted in Indian Rupees (INR).
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                You are solely responsible for complying with all applicable laws, rules, and regulations, including those in India, in connection with any payments made to Eronix.
                            </p>
                        </section>

                        {/* Use of the Platform */}
                        <section className="policy-card-block">
                            <h2>12. Use of the Platform</h2>

                            <h3 style={{ marginTop: '0.75rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Intermediary Role &amp; User Conduct</h3>
                            <p>
                                You acknowledge and agree that Eronix, operating as a proprietorship business, and its Platform act solely as an intermediary and provide hosting and technology services to users and visitors. All information, listings, content, and materials available on the Platform are generated by third-party users. Eronix does not originate, initiate, select, modify, or control the transmission of such content and has no editorial control over third-party information.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>User Information Responsibility</h3>
                            <p>
                                “Your Information” refers to all information, content, data, or material submitted by you on the Platform, including but not limited to registration details, listings, buying activity, feedback, messages, and emails. You are solely responsible for Your Information. Eronix acts only as a passive conduit for the hosting, transmission, and publication of such information.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Your Information and listings must comply with these Terms of Use, the Privacy Policy, and the Information Technology (Intermediary Guidelines) Rules, 2011. Any non-compliance may result in removal of content and/or termination or suspension of access to the Platform.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Prohibited Content and Conduct</h3>
                            <p>
                                You agree not to post, upload, transmit, or share any information or content that:
                            </p>
                            <ul style={{ marginTop: '0.5rem', paddingLeft: '1.5rem', listStyle: 'disc', columns: '2 200px' }}>
                                <li style={{ marginBottom: '0.4rem' }}>Belongs to someone else without their permission.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Is harmful, harassing, defamatory, obscene, or illegal.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Harms minors.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Infringes on intellectual property rights.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Violates any law.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Misleads users.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Impersonates someone else.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Contains harmful software.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Threatens India’s unity, security, or sovereignty.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Is misleading.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Is offensive or promotes hatred.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Harasses others.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Involves unsolicited mass mailing or “spamming”.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Promotes illegal activities.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Infringes on third-party rights.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Promotes unauthorized copies of copyrighted works.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Contains restricted or hidden access pages.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Exploits people or solicits personal information.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Provides information about illegal activities.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Contains unauthorized images or videos of others.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Tries to gain unauthorized access to the Platform.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Engages in commercial activities without our consent.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Solicits or engages in gambling.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Interferes with another user’s experience.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Links to inappropriate material.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Provides false or misleading information.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Offers prohibited items.</li>
                                <li style={{ marginBottom: '0.4rem' }}>Creates liability for us or causes service loss from our providers.</li>
                            </ul>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Platform Access and Security</h3>
                            <p>
                                You shall not use automated means, bots, scrapers, or similar technologies to access the Platform without prior written consent. You shall not attempt to gain unauthorized access to any part of the Platform, user accounts, or systems.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                You shall not make defamatory or false statements about Eronix or the Platform, interfere with operations, or disrupt Platform functionality.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Legal Compliance</h3>
                            <p>
                                You agree to use the Platform only for lawful purposes and to comply with all applicable local, state, national, and international laws and regulations.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>License to Use User Content</h3>
                            <p>
                                You grant Eronix a non-exclusive, worldwide, royalty-free license to use, host, store, reproduce, modify, display, and distribute Your Information solely as necessary to provide and improve the Platform and its services.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Accuracy of Listings</h3>
                            <p>
                                You agree to provide accurate, complete, and truthful information regarding products or services offered by you. You shall not exaggerate, misrepresent, or mislead users regarding the nature, quality, or availability of your offerings.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Communication &amp; Solicitation</h3>
                            <p>
                                You shall not solicit other users to transact outside the Platform or misuse Platform information to harass, harm, or contact users without consent. Eronix reserves the right to limit messaging or communication activity.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Disclosure &amp; Enforcement</h3>
                            <p>
                                Eronix may disclose information as required to comply with applicable laws, court orders, or government requests, or to investigate suspected illegal or fraudulent activities. Eronix may monitor, remove, or disable access to content that violates these Terms or applicable law; however, responsibility for posted content remains with the user.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Advertisers &amp; Third Parties</h3>
                            <p>
                                Your dealings with advertisers or third parties found on the Platform are solely between you and such parties. Eronix shall not be responsible or liable for any loss or damage arising from such dealings.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>User Risk Acknowledgement</h3>
                            <p>
                                You acknowledge that you may be exposed to offensive or objectionable content from other users. Eronix is not responsible for personal information voluntarily disclosed by you on the Platform.
                            </p>

                            <h3 style={{ marginTop: '1rem', fontSize: '1.1rem', color: '#1a1a2e' }}>Security &amp; Abuse</h3>
                            <p>
                                Eronix reserves the right to take appropriate legal action and claim damages for any involvement in denial-of-service (DoS), distributed denial-of-service (DDoS), hacking, or similar attacks against the Platform.
                            </p>
                        </section>

                        {/* Content Posted on Site */}
                        <section className="policy-card-block">
                            <h2>13. Content Posted on Site</h2>
                            <p>
                                The Platform hosts various types of content, including but not limited to text, graphics, photographs, trademarks, logos, sounds, music, and artwork (“Content”). Such Content is generated by third-party users and is beyond the control of Eronix, which acts solely as an intermediary under these Terms of Use.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Unless expressly stated otherwise in these Terms of Use, no part of the Platform or its Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, or mirrored in any form or by any means to any other computer, server, website, platform, or medium for publication, distribution, or commercial exploitation without the prior written consent of Eronix.
                            </p>
                        </section>

                        {/* Authorization for Contact and Call Recording */}
                        <section className="policy-card-block">
                            <h2>14. Authorization for Contact and Call Recording</h2>
                            <p>
                                By using our services, you expressly consent to receive autodialed, prerecorded, or system-generated calls and text messages from Eronix at any telephone number provided by you or otherwise lawfully obtained by us. Such communications may be made for purposes including, but not limited to:
                            </p>
                            <ul style={{ marginTop: '0.5rem', paddingLeft: '1.5rem', listStyle: 'disc' }}>
                                <li style={{ marginBottom: '0.4rem' }}>Account-related notifications, order confirmations, delivery updates, or service information;</li>
                                <li style={{ marginBottom: '0.4rem' }}>Troubleshooting account or service issues;</li>
                                <li style={{ marginBottom: '0.4rem' }}>Dispute resolution;</li>
                                <li style={{ marginBottom: '0.4rem' }}>Payment reminders or debt collection, where applicable;</li>
                                <li style={{ marginBottom: '0.4rem' }}>Surveys, feedback requests, or questionnaires;</li>
                                <li style={{ marginBottom: '0.4rem' }}>Promotional offers, marketing communications, and service updates; or</li>
                                <li style={{ marginBottom: '0.4rem' }}>Any communication necessary to manage your account, enforce these Terms of Use, applicable policies, legal obligations, or any other agreements between you and Eronix.</li>
                            </ul>
                            <p style={{ marginTop: '0.75rem' }}>
                                Standard call, SMS, or data charges imposed by your telecom service provider may apply.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                Eronix may share your phone number and other personal information with authorized third-party service providers, including but not limited to logistics partners, customer support vendors, payment processors, or collection agencies, strictly for the purpose of fulfilling its contractual, legal, or operational obligations. Such service providers may contact you using autodialed or prerecorded calls or messages, as authorized by Eronix, solely for the purposes stated above.
                            </p>
                            <p style={{ marginTop: '0.75rem' }}>
                                You further acknowledge and agree that Eronix may, without prior notice, monitor or record telephone conversations between you (or your representatives) and Eronix or its agents for quality assurance, training, compliance, dispute resolution, or to protect its legal and business interests, to the extent permitted under applicable law.
                            </p>
                        </section>

                        {/* Contact */}
                        <section className="policy-card-block">
                            <h2>15. Contact Us</h2>
                            <p>
                                If you have any questions about these Terms of Use, please contact us at{' '}
                                <a href="mailto:legal@eronixtech.com" style={{ color: '#0052cc', fontWeight: '600' }}>
                                    legal@eronixtech.com
                                </a>
                                .
                            </p>
                        </section>

                        {/* Visual Process Workflow Steps */}
                        <section className="policy-card-block">
                            <h2>Our Commitment to You</h2>
                            <div className="policy-steps-workflow">
                                <div className="workflow-card">
                                    <div className="card-step-num">Transparent Policies</div>
                                    <div className="card-icon-container">
                                        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#0052cc" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                                            <polyline points="9 12 11 14 15 10" />
                                        </svg>
                                    </div>
                                </div>
                                <div className="workflow-card">
                                    <div className="card-step-num">Secure &amp; Reliable</div>
                                    <div className="card-icon-container">
                                        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#0052cc" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                            <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
                                            <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                                        </svg>
                                    </div>
                                </div>
                                <div className="workflow-card">
                                    <div className="card-step-num">Dedicated Support</div>
                                    <div className="card-icon-container">
                                        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#0052cc" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                            <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
                                        </svg>
                                    </div>
                                </div>
                                <div className="workflow-card">
                                    <div className="card-step-num">Fair &amp; Equitable</div>
                                    <div className="card-icon-container">
                                        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#0052cc" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                            <circle cx="12" cy="12" r="10" />
                                            <path d="M12 6v6l4 2" />
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        </section>

                    </main>

                    {/* Right Sidebar Widget Column */}
                    <aside className="policy-sidebar-column">
                        <div className="help-sticky-card">
                            <h3>Need a Help?</h3>
                            <ul className="contact-links-list">
                                <li>
                                    <span className="contact-icon">📞</span>
                                    <a href="tel:+919922202003">+91- 9922202003</a>
                                </li>
                                <li>
                                    <span className="contact-icon">💬</span>
                                    <a href="#whatsapp">Whatsapp</a>
                                </li>
                                <li>
                                    <span className="contact-icon">🔔</span>
                                    <a href="#telegram">Telegram</a>
                                </li>
                                <li>
                                    <span className="contact-icon">✉️</span>
                                    <a href="mailto:sales@eronixtech.com" className="email-link">sales@eronixtech.com</a>
                                </li>
                            </ul>

                            <div className="sidebar-divider"></div>

                            <h4>Subscribe us</h4>
                            <div className="social-action-buttons">
                                <a href="#x" className="social-btn platform-x">
                                    <svg width="14" height="14" viewBox="0 0 24 24" fill="#fff"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" /></svg>
                                </a>
                                <a href="#whatsapp" className="social-btn platform-wa">
                                    <svg width="16" height="16" viewBox="0 0 24 24" fill="#fff"><path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.514 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.713-1.455L0 24zm6.59-4.846c1.6.95 3.188 1.449 4.825 1.451 5.436 0 9.86-4.42 9.863-9.855.001-2.633-1.02-5.107-2.875-6.964C16.547 1.928 14.08 .908 11.457 .908c-5.436 0-9.86 4.42-9.864 9.856-.001 1.716.452 3.39 1.308 4.869l-.993 3.628 3.71-.973z" /></svg>
                                </a>
                            </div>
                        </div>
                    </aside>

                </div> {/* End of policy-grid-layout */}

                {/* Full-width sections below the grid */}
                <div className="policy-fullwidth-sections">
                    <section className="policy-card-block online-store-section">
                        <h2>Online store of household appliances and electronics</h2>
                        <p>
                            Eronix Technologies is not just a support hub – we are a full-fledged online store offering
                            a wide range of household appliances, consumer electronics, and smart devices. From kitchen
                            essentials like mixers, microwaves, and refrigerators to entertainment systems, laptops,
                            and smartphones, we bring you the latest technology at competitive prices.
                        </p>
                        <p>
                            Our platform is designed to make your shopping experience seamless: easy product discovery,
                            secure payment options, fast delivery, and dedicated after-sales support. Whether you're
                            upgrading your home or looking for the perfect gadget gift, Eronix has you covered.
                        </p>
                        <p>
                            We partner with leading brands and trusted suppliers to ensure quality and reliability.
                            Plus, our return and warranty policies are crafted to give you peace of mind with every
                            purchase. Explore our catalog and discover the future of home electronics today.
                        </p>
                    </section>

                    <section className="policy-card-block store-locations-section">
                        <div className="store-cards-container">
                            <div className="store-card">
                                <h3>
                                    <FaChevronRight className="store-icon" />
                                    Bengaluru Store
                                </h3>
                                <p>
                                    Golden Green Layout, 76 5th Cross, Thurahalli Rd, opp. Jayanagar Housing Society,
                                    <br />
                                    Subramanyapura, Bengaluru, Karnataka 560061
                                </p>
                            </div>

                            <div className="store-card">
                                <h3>
                                    <FaChevronRight className="store-icon" />
                                    Solapur Store
                                </h3>
                                <p>
                                    01, Jijamata Complex, near India Tea, opp. Sangameshwar College,
                                    <br />
                                    Sat Rasta, Solapur, Maharashtra 413001, India
                                </p>
                            </div>
                        </div>
                    </section>
                </div>

            </div>
        </Layout>
    );
};

export default TermsOfUse;